# Generated by Django 4.1 on 2022-10-18 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('socially', '0002_rename_social_socially'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=500)),
                ('comment_time', models.DateTimeField(null=True)),
                ('shared', models.BooleanField(default=False)),
                ('shared_time', models.DateTimeField(null=True)),
                ('saved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='socially',
            name='interaction',
            field=models.ManyToManyField(through='socially.Action', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socially',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='socially',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socially.socially'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
