# Generated by Django 4.1 on 2022-10-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socially', '0003_action_socially_interaction_alter_socially_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socially',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
