# Generated by Django 4.1 on 2022-10-19 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socially', '0003_action_socially_interaction_alter_socially_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='action',
            name='comment_time',
        ),
        migrations.RemoveField(
            model_name='action',
            name='like',
        ),
        migrations.RemoveField(
            model_name='action',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='action',
            name='shared',
        ),
        migrations.RemoveField(
            model_name='action',
            name='shared_time',
        ),
        migrations.AddField(
            model_name='socially',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
