# Generated by Django 4.1 on 2022-10-18 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socially', '0004_socially_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socially',
            name='like',
        ),
        migrations.RemoveField(
            model_name='action',
            name='like',
        ),
        migrations.AddField(
            model_name='action',
            name='like',
            field=models.ManyToManyField(related_name='social_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
