# Generated by Django 4.1 on 2022-10-18 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socially', '0005_remove_socially_like_remove_action_like_action_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='like',
            field=models.ManyToManyField(related_name='sociallys', to=settings.AUTH_USER_MODEL),
        ),
    ]
